# Erzeugt services/daten/daily.json (seit App 0.42.0; vorher src/content/ – war öffentlich abrufbar): Tagesinhalte für 31 Tage (26.09.–26.10.2026).
# Alle Texte sind eigene Service-Inhalte (keine Nachrichten, keine Anlageempfehlungen).
import json, datetime, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from quiz_2026_10 import QUIZ   # Quiz zum Mitmachen (Phase 3, App 0.52.0) – eigene Datei, weil lang

START = datetime.date(2026, 9, 26)

RAETSEL = [
 ("Was hat Zähne, kann aber nicht beißen?", "Ein Kamm."),
 ("Je mehr man davon wegnimmt, desto größer wird es. Was ist es?", "Ein Loch."),
 ("Was wird nasser, je mehr es trocknet?", "Ein Handtuch."),
 ("Was hat einen Hals, aber keinen Kopf?", "Eine Flasche."),
 ("Was gehört dir, wird aber von anderen viel öfter benutzt als von dir?", "Dein Name."),
 ("Welcher Monat hat 28 Tage?", "Alle Monate."),
 ("Was kann man brechen, ohne es zu berühren?", "Ein Versprechen."),
 ("Was hat Blätter, ist aber kein Baum?", "Ein Buch."),
 ("Was steht genau in der Mitte von Paris?", "Der Buchstabe R."),
 ("Was hat viele Tasten, öffnet aber keine einzige Tür?", "Ein Klavier."),
 ("Was kommt einmal im Monat vor, zweimal im Moment, aber nie in einer Stunde?", "Der Buchstabe M."),
 ("Was hat ein Auge, kann aber nicht sehen?", "Eine Nadel."),
 ("Was fällt, ohne sich jemals wehzutun?", "Regen."),
 ("Was ist leichter als eine Feder, und doch kann es selbst der Stärkste nicht lange halten?", "Der Atem."),
 ("Was geht durch Glas, ohne es zu zerbrechen?", "Licht."),
 ("Was hat Zeiger, kann aber nichts zeigen außer der Zeit?", "Eine Uhr."),
 ("Was geht morgens auf vier, mittags auf zwei und abends auf drei Beinen?", "Der Mensch: als Baby krabbelnd, als Erwachsener aufrecht, im Alter mit Gehstock."),
 ("Was ist voller Löcher und hält trotzdem Wasser?", "Ein Schwamm."),
 ("Was reist um die ganze Welt und bleibt dabei immer in seiner Ecke?", "Eine Briefmarke."),
 ("Was wird größer, wenn man es auf den Kopf stellt?", "Die Zahl 6 – sie wird zur 9."),
 ("Was hat ein Kopfende und ein Fußende, aber keinen Körper?", "Ein Bett."),
 ("Schwarz beim Kauf, rot beim Benutzen, grau beim Wegwerfen. Was ist es?", "Holzkohle."),
 ("Was hat einen Daumen und vier Finger, lebt aber nicht?", "Ein Handschuh."),
 ("Was kann man sich einfangen, aber nicht werfen?", "Eine Erkältung."),
 ("Was ist immer vor dir, und doch kannst du es nie sehen?", "Die Zukunft."),
 ("Was brennt, ist aber kein Feuer?", "Die Brennnessel."),
 ("Man hört es, sieht es nie, und es antwortet nur, wenn man es anspricht. Was ist es?", "Ein Echo."),
 ("Was wird umso kürzer, je länger es brennt?", "Eine Kerze."),
 ("Welches Tier trägt eine große Zahl im Namen, hat aber längst nicht so viele Beine?", "Der Tausendfüßer."),
 ("Was ist schwerer: ein Kilo Federn oder ein Kilo Eisen?", "Keins – beide wiegen ein Kilo."),
 ("Was hat vier Beine, kann aber nicht laufen?", "Ein Tisch."),
]

# Mitmachen (Phase 2, App 0.50.0): je Rätsel die kurze richtige Antwort (Knopf), 3 falsche Antworten und bis zu 2 Tipps.
# Falsche Antworten müssen eindeutig falsch sein (Roger prüft vollständig, Entscheidung 0a/15); die Reihenfolge mischt der Browser je Tag.
MITMACHEN = [
 ("Ein Kamm", ["Eine Gabel", "Eine Bürste", "Ein Hai"], ["Du benutzt ihn morgens vor dem Spiegel.", "Er gehört zu den Haaren."]),
 ("Ein Loch", ["Ein Sandhaufen", "Eine Pfütze", "Ein Stapel"], ["Denk an eine Schaufel.", "Eigentlich besteht es aus … nichts."]),
 ("Ein Handtuch", ["Ein Regenschirm", "Ein Föhn", "Die Wäsche"], ["Es hängt oft im Bad.", "Man braucht es nach dem Duschen."]),
 ("Eine Flasche", ["Eine Giraffe", "Ein Schal", "Ein Hut"], ["Man kann daraus trinken.", "Oben hat sie einen Deckel oder Korken."]),
 ("Dein Name", ["Dein Handy", "Dein Auto", "Deine Zahnbürste"], ["Man kann es nicht anfassen.", "Andere rufen dich damit."]),
 ("Alle Monate", ["Der Februar", "Kein Monat", "Nur Monate mit 30 Tagen"], ["In der Frage steht nicht „genau“.", "Auch der Januar hat einen 28. Tag."]),
 ("Ein Versprechen", ["Ein Ast", "Ein Teller", "Ein Bleistift"], ["Es besteht nur aus Worten.", "Man gibt es jemandem – und sollte es halten."]),
 ("Ein Buch", ["Ein Stuhl", "Eine Kerze", "Ein Teller"], ["Es steht oft in einem Regal.", "Man blättert darin."]),
 ("Der Buchstabe R", ["Der Eiffelturm", "Der Louvre", "Die Seine"], ["Denk nicht an die Stadt, sondern an das Wort.", "Paris hat fünf Buchstaben."]),
 ("Ein Klavier", ["Ein Schlüsselbund", "Eine Trommel", "Eine Geige"], ["Es macht Musik.", "Die Tasten sind schwarz und weiß."]),
 ("Der Buchstabe M", ["Der Buchstabe O", "Der Buchstabe N", "Der Vollmond"], ["Schau dir die Wörter selbst an.", "Zähle die Buchstaben in „Moment“."]),
 ("Eine Nadel", ["Eine Schere", "Ein Knopf", "Ein Faden"], ["Man braucht dazu einen Faden.", "Man näht damit."]),
 ("Regen", ["Ein Glas", "Ein Ei", "Ein Kletterer"], ["Es kommt von oben.", "Danach braucht man einen Schirm."]),
 ("Der Atem", ["Ein Luftballon", "Ein Blatt Papier", "Ein Haar"], ["Du tust es den ganzen Tag, ohne nachzudenken.", "Beim Tauchen merkst du es."]),
 ("Licht", ["Wasser", "Ein Stein", "Ein Vogel"], ["Ohne es wäre ein Fenster nutzlos.", "Es kommt von der Sonne."]),
 ("Eine Uhr", ["Ein Tacho", "Ein Kalender", "Ein Wegweiser"], ["Sie tickt oft.", "Man trägt sie am Handgelenk oder hängt sie an die Wand."]),
 ("Der Mensch", ["Ein Hund", "Ein Pferd", "Ein Tisch"], ["Morgen, Mittag und Abend stehen für ein ganzes Leben.", "Am Abend hilft ein Stock."]),
 ("Ein Schwamm", ["Ein Sieb", "Ein Eimer", "Ein Netz"], ["Man findet ihn in der Küche.", "Man drückt ihn aus."]),
 ("Eine Briefmarke", ["Ein Flugzeug", "Ein Koffer", "Ein Globus"], ["Sie klebt.", "Man findet sie auf einem Brief."]),
 ("Die Zahl 6", ["Die Zahl 8", "Die Zahl 9", "Die Zahl 1"], ["Es ist eine Ziffer.", "Dreh sie um 180 Grad."]),
 ("Ein Bett", ["Ein Tisch", "Ein Schrank", "Ein Teppich"], ["Es steht im Schlafzimmer.", "Darauf liegt dein Kissen."]),
 ("Holzkohle", ["Eine Tomate", "Ein Ziegelstein", "Tinte"], ["Sie glüht.", "Man braucht sie zum Grillen."]),
 ("Ein Handschuh", ["Eine Socke", "Ein Schuh", "Ein Ring"], ["Im Winter ist er praktisch.", "Meist kommt er im Paar."]),
 ("Eine Erkältung", ["Einen Ball", "Einen Fisch", "Ein Frisbee"], ["Danach braucht man Taschentücher.", "Sie kommt oft im Herbst."]),
 ("Die Zukunft", ["Dein Rücken", "Der Horizont", "Die Vergangenheit"], ["Es ist keine Sache, sondern eine Zeit.", "Morgen gehört dazu."]),
 ("Die Brennnessel", ["Eine Kerze", "Ein Kamin", "Die Rose"], ["Sie wächst am Wegrand.", "Wer sie anfasst, bekommt rote Pusteln."]),
 ("Ein Echo", ["Ein Radio", "Der Wind", "Ein Telefon"], ["Am besten klappt es in den Bergen.", "Es wiederholt deine Worte."]),
 ("Eine Kerze", ["Ein Kamin", "Eine Glühbirne", "Ein Ofen"], ["Sie steht gern auf dem Adventskranz.", "Sie ist aus Wachs."]),
 ("Der Tausendfüßer", ["Die Spinne", "Der Regenwurm", "Die Raupe"], ["Er lebt unter Steinen und Laub.", "Die Zahl hat drei Nullen."]),
 ("Beide gleich schwer", ["Das Kilo Eisen", "Das Kilo Federn", "Kommt auf die Größe an"], ["Lies die Mengen genau.", "Ein Kilo ist ein Kilo."]),
 ("Ein Tisch", ["Ein Hund", "Eine Lampe", "Ein Teppich"], ["Daran isst man.", "Man stellt Teller darauf."]),
]

WITZE = [
 "Treffen sich zwei Magnete. Sagt der eine: „Was soll ich heute bloß anziehen?“",
 "Was macht ein Pirat am Computer? – Er drückt die Enter-Taste.",
 "Warum können Seeräuber keinen Kreis berechnen? – Weil sie Pi raten.",
 "Was ist grün und klopft an die Tür? – Ein Klopfsalat.",
 "Wie nennt man einen Bumerang, der nicht zurückkommt? – Stock.",
 "Was sagt der große Stift zum kleinen Stift? – „Wachs mal, Stift!“",
 "Was ist orange und läuft durch den Wald? – Eine Wanderine.",
 "Was macht ein Clown im Büro? – Faxen.",
 "Welcher Bus hat den Atlantik überquert? – Kolumbus.",
 "Was sitzt auf dem Baum und ruft „Aha“? – Ein Uhu mit Sprachfehler.",
 "Wie heißt der Bruder von Elvis? – Zwölfis.",
 "Was liegt am Strand und spricht undeutlich? – Eine Nuschel.",
 "Was ist ein Keks unter einem Baum? – Ein schattiges Plätzchen.",
 "Wo wohnen Katzen am liebsten? – Im Miezhaus.",
 "Was ist weiß und stört beim Essen? – Eine Lawine.",
 "Was macht ein Mathematiker im Garten? – Er zieht Wurzeln.",
 "Wie nennt man einen Schneemann mit Sonnenbrand? – Pfütze.",
 "Was ist klein, braun und rund und sitzt hinter Gittern? – Eine Knastanie.",
 "Was ist ein Cowboy ohne Pferd? – Ein Sattelschlepper.",
 "Warum sind Fische so schlau? – Weil sie in Schulen gehen.",
 "Was ist groß, grau und telefoniert? – Ein Telefant.",
 "Warum können Gespenster so schlecht lügen? – Weil man durch sie hindurchsieht.",
 "Was sagt die Null zur Acht? – „Schicker Gürtel!“",
 "Was trinkt ein Vampir am liebsten zum Frühstück? – Blutorangensaft.",
 "Warum wurde die Tomate rot? – Sie hat das Salatdressing gesehen.",
 "Was macht ein Schaf beim Sport? – Määärathon.",
 "Welche Stadt hat keine Häuser? – Die Werkstatt.",
 "Was ist braun und sitzt im Wald auf dem Klavier? – Ein Brummbär mit Lampenfieber.",
 "Was ist gelb und schießt? – Eine Banone.",
 "Was steht auf dem Grabstein eines Mathematikers? – „Damit hat er nicht gerechnet.“",
 "Was ist ein Keller voller Kekse? – Ein Krümelkeller.",
]

WORTE = [
 ("Kairos", "der richtige, günstige Augenblick, den man ergreifen sollte", "Altgriechisch"),
 ("Fernweh", "Sehnsucht nach fernen Orten – das Gegenstück zum Heimweh", "Deutsch"),
 ("Serendipität", "ein glücklicher Zufallsfund, nach dem man gar nicht gesucht hat", "von engl. serendipity, nach dem Märchen von den drei Prinzen von Serendip"),
 ("Hygge", "entspannte, warme Gemütlichkeit – etwa mit Kerzen, Tee und guten Leuten", "Dänisch"),
 ("Kummerspeck", "Gewicht, das man sich aus Frust oder Kummer angegessen hat", "Deutsch"),
 ("Lagom", "genau richtig – nicht zu viel und nicht zu wenig", "Schwedisch"),
 ("Ikigai", "das, wofür es sich zu leben lohnt; der Grund, morgens aufzustehen", "Japanisch"),
 ("Sisu", "zähe Ausdauer und innere Stärke, auch wenn es schwierig wird", "Finnisch"),
 ("Schadenfreude", "Freude über das Missgeschick anderer", "Deutsch, als Lehnwort auch im Englischen"),
 ("Wanderlust", "Lust aufs Unterwegssein; im Englischen als Lehnwort gebräuchlich", "Deutsch"),
 ("Fingerspitzengefühl", "feines Gespür für eine heikle Situation", "Deutsch"),
 ("Zeitgeist", "die typische Denk- und Lebensweise einer Epoche", "Deutsch, weltweit übernommen"),
 ("Weltschmerz", "Traurigkeit über die Unvollkommenheit der Welt", "Deutsch, geprägt durch Jean Paul"),
 ("Ohrwurm", "eine Melodie, die einem nicht mehr aus dem Kopf geht", "Deutsch"),
 ("Torschlusspanik", "Angst, eine Gelegenheit endgültig zu verpassen", "Deutsch – ursprünglich die Eile vor dem Schließen der Stadttore"),
 ("verschlimmbessern", "etwas verbessern wollen und es dabei schlimmer machen", "Deutsch"),
 ("Luftschloss", "ein schöner, aber unrealistischer Plan", "Deutsch"),
 ("Treppenwitz", "die schlagfertige Antwort, die einem erst zu spät einfällt", "Deutsch, nach frz. „esprit de l’escalier“"),
 ("Feierabend", "das Ende des Arbeitstags und die freie Zeit danach", "Deutsch"),
 ("Geborgenheit", "das Gefühl, sicher und gut aufgehoben zu sein", "Deutsch"),
 ("Wabi-Sabi", "die Schönheit des Unvollkommenen und Vergänglichen", "Japanisch"),
 ("Saudade", "wehmütige Sehnsucht nach etwas, das fehlt", "Portugiesisch"),
 ("Ubuntu", "Menschlichkeit und Gemeinschaftssinn: „Ich bin, weil wir sind“", "aus den Nguni-Bantusprachen"),
 ("Sitzfleisch", "die Ausdauer, lange bei einer Sache zu bleiben", "Deutsch"),
 ("Eselsbrücke", "eine Merkhilfe für etwas, das man sich schwer merken kann", "Deutsch"),
 ("Lampenfieber", "Aufregung vor einem Auftritt", "Deutsch – nach den Lampen der Bühne"),
 ("Kopfkino", "Bilder und Szenen, die sich in der Vorstellung abspielen", "Deutsch"),
 ("Waldeinsamkeit", "das Gefühl, allein und im Einklang mit dem Wald zu sein", "Deutsch, geprägt in der Romantik (Ludwig Tieck)"),
 ("Muße", "freie Zeit ohne Zweck und Druck", "Deutsch, von althochdeutsch „muoza“"),
 ("Kaizen", "ständige Verbesserung in vielen kleinen Schritten", "Japanisch"),
 ("Hüftgold", "scherzhaft für ein kleines Fettpölsterchen an der Hüfte", "Deutsch, umgangssprachlich"),
]

SPRICHWOERTER = [
 "Aller Anfang ist schwer.", "Übung macht den Meister.", "Morgenstund hat Gold im Mund.",
 "Wer rastet, der rostet.", "Gut Ding will Weile haben.", "Ende gut, alles gut.",
 "Viele Köche verderben den Brei.", "Kleinvieh macht auch Mist.", "Wer A sagt, muss auch B sagen.",
 "Stille Wasser sind tief.", "Der Apfel fällt nicht weit vom Stamm.", "Was du heute kannst besorgen, das verschiebe nicht auf morgen.",
 "Ohne Fleiß kein Preis.", "Reden ist Silber, Schweigen ist Gold.", "Wo ein Wille ist, ist auch ein Weg.",
 "Eile mit Weile.", "Lügen haben kurze Beine.", "Geteilte Freude ist doppelte Freude.",
 "Hunger ist der beste Koch.", "Wer zuletzt lacht, lacht am besten.", "Es ist noch kein Meister vom Himmel gefallen.",
 "Einem geschenkten Gaul schaut man nicht ins Maul.", "Steter Tropfen höhlt den Stein.", "Wie man in den Wald hineinruft, so schallt es heraus.",
 "Man soll den Tag nicht vor dem Abend loben.", "Doppelt genäht hält besser.", "Kommt Zeit, kommt Rat.",
 "Probieren geht über Studieren.", "In der Ruhe liegt die Kraft.", "Wer nicht wagt, der nicht gewinnt.",
 "Auf Regen folgt Sonnenschein.",
]

# (Name, Minuten, vegetarisch, Zutaten für 2, Zubereitung)
REZEPTE = [
 ("Ofengemüse mit Feta", 35, True, ["2 Paprika", "1 Zucchini", "1 rote Zwiebel", "200 g Feta", "2 EL Olivenöl", "Oregano, Salz, Pfeffer"], "Gemüse würfeln, mit Öl und Gewürzen mischen und bei 200 °C etwa 20 Minuten backen. Feta zerbröseln, darüberstreuen und weitere 10 Minuten backen."),
 ("Kürbissuppe mit Ingwer", 35, True, ["1 kleiner Hokkaido (ca. 800 g)", "1 Zwiebel", "1 Stück Ingwer (2 cm)", "600 ml Gemüsebrühe", "100 ml Kokosmilch", "Salz, Pfeffer"], "Kürbis mit Schale würfeln, mit Zwiebel und Ingwer andünsten, mit Brühe 20 Minuten köcheln. Kokosmilch dazu, fein pürieren und abschmecken."),
 ("Linsen-Dal", 30, True, ["150 g rote Linsen", "1 Zwiebel", "1 Knoblauchzehe", "1 Dose Tomaten", "200 ml Kokosmilch", "1 TL Curry, ½ TL Kurkuma"], "Zwiebel und Knoblauch anbraten, Gewürze kurz mitrösten. Linsen, Tomaten, Kokosmilch und 200 ml Wasser dazu und 15 Minuten köcheln. Mit Reis oder Brot servieren."),
 ("Kartoffel-Lauch-Suppe", 30, True, ["500 g Kartoffeln", "1 Stange Lauch", "700 ml Gemüsebrühe", "50 ml Sahne", "Muskat, Salz, Pfeffer"], "Kartoffeln würfeln, Lauch in Ringe schneiden, beides andünsten. Mit Brühe 20 Minuten garen, teilweise pürieren, Sahne einrühren und würzen."),
 ("Spaghetti aglio e olio", 15, True, ["200 g Spaghetti", "3 Knoblauchzehen", "4 EL Olivenöl", "1 getrocknete Chili", "Petersilie", "Parmesan nach Wunsch"], "Spaghetti kochen. Knoblauch in Scheiben mit Chili sanft im Öl erwärmen, nicht bräunen. Nudeln mit etwas Kochwasser und Petersilie darin schwenken."),
 ("Pilzpfanne mit Semmelknödeln", 30, True, ["400 g Champignons", "1 Zwiebel", "150 ml Sahne", "Petersilie", "4 Semmelknödel (Fertigprodukt oder vom Vortag)"], "Knödel nach Packung garen. Pilze scharf anbraten, Zwiebel dazu, mit Sahne ablöschen, einköcheln lassen und mit Petersilie servieren."),
 ("Hähnchen-Gemüse-Curry", 30, False, ["300 g Hähnchenbrust", "1 Paprika", "1 Handvoll Brokkoli", "200 ml Kokosmilch", "1 EL Currypaste", "Reis"], "Hähnchen in Streifen anbraten, Gemüse dazu. Currypaste einrühren, mit Kokosmilch ablöschen und 10 Minuten köcheln. Mit Reis servieren."),
 ("Flammkuchen mit Apfel und Zwiebel", 25, True, ["1 Flammkuchenteig", "150 g Schmand", "1 Apfel", "1 rote Zwiebel", "Thymian, Salz, Pfeffer"], "Teig mit gewürztem Schmand bestreichen, mit dünnen Apfel- und Zwiebelscheiben belegen. Bei 220 °C etwa 12 Minuten backen, mit Thymian bestreuen."),
 ("Rote-Bete-Salat mit Walnüssen", 20, True, ["2 gekochte Rote Bete", "1 Apfel", "1 Handvoll Walnüsse", "Feldsalat", "Essig, Öl, Senf, Honig"], "Rote Bete und Apfel in Stücke schneiden, Walnüsse kurz rösten. Aus Essig, Öl, Senf und Honig ein Dressing rühren und alles auf dem Feldsalat anrichten."),
 ("Kartoffelpuffer mit Apfelmus", 35, True, ["600 g Kartoffeln", "1 Zwiebel", "1 Ei", "2 EL Mehl", "Öl zum Braten", "Apfelmus"], "Kartoffeln und Zwiebel reiben, gut ausdrücken, mit Ei, Mehl und Salz mischen. Flache Puffer in heißem Öl goldbraun braten. Mit Apfelmus servieren."),
 ("Gnocchi mit Salbeibutter", 15, True, ["500 g Gnocchi", "50 g Butter", "8 Salbeiblätter", "Parmesan"], "Gnocchi garen, bis sie oben schwimmen. Butter mit Salbei aufschäumen, Gnocchi darin schwenken und mit Parmesan bestreuen."),
 ("Chili sin Carne", 40, True, ["1 Dose Kidneybohnen", "1 Dose Mais", "1 Dose Tomaten", "1 Paprika", "1 Zwiebel", "Kreuzkümmel, Paprikapulver, Chili"], "Zwiebel und Paprika anbraten, Gewürze kurz mitrösten. Tomaten, Bohnen und Mais dazu und 25 Minuten köcheln. Mit Brot oder Reis servieren."),
 ("Lachs mit Ofenkartoffeln", 40, False, ["2 Lachsfilets", "500 g kleine Kartoffeln", "1 Zitrone", "Dill", "Olivenöl"], "Kartoffeln halbieren, mit Öl und Salz 25 Minuten bei 200 °C backen. Lachs dazulegen, mit Zitrone beträufeln und 12 Minuten mitgaren. Mit Dill servieren."),
 ("Käsespätzle", 30, True, ["400 g Spätzle", "150 g Bergkäse", "2 Zwiebeln", "Butter", "Schnittlauch"], "Zwiebeln in Ringen in Butter goldbraun braten. Spätzle erhitzen und abwechselnd mit geriebenem Käse schichten. Mit Röstzwiebeln und Schnittlauch servieren."),
 ("Gemüse-Frittata", 25, True, ["5 Eier", "1 Zucchini", "1 Handvoll Spinat", "50 g Parmesan", "Salz, Pfeffer"], "Gemüse in einer ofenfesten Pfanne anbraten. Verquirlte Eier mit Käse darübergießen, stocken lassen und 8 Minuten bei 180 °C im Ofen fertig garen."),
 ("Kürbis-Risotto", 40, True, ["200 g Risottoreis", "300 g Kürbis", "1 Zwiebel", "800 ml Brühe", "50 g Parmesan", "Butter"], "Zwiebel und Kürbiswürfel andünsten, Reis glasig werden lassen. Nach und nach Brühe zugeben und rühren, bis der Reis cremig ist. Butter und Parmesan unterziehen."),
 ("Ofenlachs-Bowl mit Reis", 30, False, ["2 Lachsfilets", "150 g Reis", "1 Avocado", "1 Karotte", "Sojasauce, Sesam"], "Reis kochen, Lachs 12 Minuten bei 200 °C backen. Mit Avocado, geraspelter Karotte, Sojasauce und Sesam in Schalen anrichten."),
 ("Tomatensuppe mit Grilled Cheese", 25, True, ["2 Dosen Tomaten", "1 Zwiebel", "400 ml Brühe", "4 Scheiben Toast", "Käse, Butter"], "Zwiebel andünsten, Tomaten und Brühe 15 Minuten köcheln, pürieren. Toast mit Käse belegen, zuklappen und in Butter goldbraun braten."),
 ("Zwiebelkuchen vom Blech (klein)", 50, False, ["1 Pizzateig", "3 Zwiebeln", "50 g Speckwürfel", "150 g Schmand", "1 Ei", "Kümmel"], "Zwiebeln und Speck andünsten, mit Schmand und Ei mischen. Auf dem Teig verteilen, mit Kümmel bestreuen und bei 200 °C 25 Minuten backen."),
 ("Couscous-Salat", 20, True, ["150 g Couscous", "1 Gurke", "10 Kirschtomaten", "Minze und Petersilie", "Zitrone, Olivenöl"], "Couscous mit heißem Wasser übergießen und quellen lassen. Gemüse würfeln, Kräuter hacken und alles mit Zitrone, Öl und Salz mischen."),
 ("Rinderhack-Pfanne mit Paprika", 25, False, ["300 g Rinderhack", "2 Paprika", "1 Zwiebel", "1 Dose Tomaten", "Paprikapulver", "Reis oder Brot"], "Hack krümelig anbraten, Zwiebel und Paprika mitbraten. Tomaten und Gewürze dazu und 10 Minuten köcheln."),
 ("Ofenkürbis mit Kichererbsen", 40, True, ["½ Butternut-Kürbis", "1 Dose Kichererbsen", "1 rote Zwiebel", "Joghurt", "Kreuzkümmel, Paprika"], "Kürbis würfeln, mit Kichererbsen, Zwiebel, Öl und Gewürzen 30 Minuten bei 200 °C backen. Mit einem Klecks Joghurt servieren."),
 ("Pasta mit Brokkoli und Zitrone", 20, True, ["200 g Pasta", "1 Brokkoli", "1 Knoblauchzehe", "1 Zitrone (Abrieb und Saft)", "Parmesan"], "Brokkoliröschen die letzten 4 Minuten mit der Pasta kochen. Mit angebratenem Knoblauch, Zitrone, etwas Kochwasser und Parmesan mischen."),
 ("Shakshuka", 25, True, ["1 Dose Tomaten", "1 Paprika", "1 Zwiebel", "4 Eier", "Kreuzkümmel, Paprikapulver", "Brot"], "Zwiebel und Paprika anbraten, Tomaten und Gewürze 10 Minuten köcheln. Mulden formen, Eier hineinschlagen und zugedeckt stocken lassen."),
 ("Bratkartoffeln mit Spiegelei", 30, True, ["600 g gekochte Kartoffeln vom Vortag", "1 Zwiebel", "4 Eier", "Butterschmalz", "Schnittlauch"], "Kartoffeln in Scheiben knusprig braten, Zwiebel dazu. Spiegeleier braten und mit Schnittlauch servieren."),
 ("Gemüsesuppe mit Graupen", 45, True, ["80 g Graupen", "2 Karotten", "1 Stück Sellerie", "1 Stange Lauch", "1 l Brühe", "Petersilie"], "Gemüse würfeln und andünsten, Graupen und Brühe dazu und 35 Minuten köcheln. Mit Petersilie servieren."),
 ("Wraps mit Hähnchen und Salat", 20, False, ["4 Tortillas", "250 g Hähnchenbrust", "Salat, Tomate, Gurke", "Joghurt-Dip"], "Hähnchen würzen und in Streifen braten. Tortillas kurz erwärmen, mit Salat, Gemüse, Hähnchen und Dip füllen und einrollen."),
 ("Apfel-Pfannkuchen", 25, True, ["150 g Mehl", "250 ml Milch", "2 Eier", "2 Äpfel", "Zimt und Zucker"], "Teig aus Mehl, Milch und Eiern rühren. Apfelscheiben in der Pfanne anbraten, Teig darübergießen und von beiden Seiten backen. Mit Zimtzucker bestreuen."),
 ("Blumenkohl-Curry", 35, True, ["1 Blumenkohl", "1 Dose Kichererbsen", "200 ml Kokosmilch", "1 Dose Tomaten", "Currypulver", "Reis"], "Blumenkohlröschen mit Curry anbraten, Tomaten, Kokosmilch und Kichererbsen dazu und 20 Minuten köcheln. Mit Reis servieren."),
 ("Kartoffelgratin", 60, True, ["800 g Kartoffeln", "200 ml Sahne", "100 ml Milch", "1 Knoblauchzehe", "80 g Käse", "Muskat"], "Kartoffeln in dünne Scheiben schneiden und in eine gefettete Form schichten. Mit gewürzter Sahne-Milch übergießen, Käse darüber und bei 180 °C 45 Minuten backen."),
 ("Kürbis-Pasta", 25, True, ["200 g Pasta", "300 g Kürbis", "1 Knoblauchzehe", "100 ml Sahne", "Parmesan, Salbei"], "Kürbiswürfel mit Knoblauch weich dünsten, mit Sahne pürieren. Mit der Pasta, etwas Kochwasser und Parmesan mischen, mit Salbei servieren."),
]

LAENDER = [
 ("Portugal", "Lissabon", "Portugiesisch", "Euro", "Bacalhau (Stockfisch)", "Portugal ist der größte Korkproduzent der Welt."),
 ("Norwegen", "Oslo", "Norwegisch", "Norwegische Krone", "Fårikål (Lamm mit Kohl)", "Mit Fjorden und Inseln ist die Küstenlinie über 100.000 km lang."),
 ("Japan", "Tokio", "Japanisch", "Yen", "Sushi", "Japan besteht aus über 14.000 Inseln."),
 ("Mexiko", "Mexiko-Stadt", "Spanisch", "Mexikanischer Peso", "Mole poblano", "Mais wurde vor rund 9.000 Jahren in Mexiko domestiziert."),
 ("Italien", "Rom", "Italienisch", "Euro", "Risotto und Pasta", "Italien hat die meisten UNESCO-Welterbestätten der Welt."),
 ("Kanada", "Ottawa", "Englisch und Französisch", "Kanadischer Dollar", "Poutine", "Kanada hat die längste Küstenlinie aller Länder."),
 ("Marokko", "Rabat", "Arabisch und Tamazight", "Dirham", "Tajine", "Die Universität al-Qarawiyyin in Fès (gegründet 859) gilt als älteste noch bestehende Hochschule."),
 ("Island", "Reykjavík", "Isländisch", "Isländische Krone", "Plokkfiskur (Fischeintopf)", "Island hat keine eigene Armee."),
 ("Griechenland", "Athen", "Griechisch", "Euro", "Moussaka", "Zu Griechenland gehören rund 6.000 Inseln, von denen nur etwa 200 bewohnt sind."),
 ("Vietnam", "Hanoi", "Vietnamesisch", "Đồng", "Phở (Nudelsuppe)", "Vietnam ist der zweitgrößte Kaffeeproduzent der Welt."),
 ("Peru", "Lima", "Spanisch und Quechua", "Sol", "Ceviche", "In Peru gibt es mehrere Tausend Kartoffelsorten."),
 ("Schweden", "Stockholm", "Schwedisch", "Schwedische Krone", "Köttbullar", "Das Jedermannsrecht erlaubt, fast überall in der Natur zu wandern und für eine Nacht zu zelten."),
 ("Indien", "Neu-Delhi", "Hindi, Englisch und viele weitere", "Indische Rupie", "Dal und Biryani", "Seit 2023 ist Indien das bevölkerungsreichste Land der Erde."),
 ("Irland", "Dublin", "Irisch und Englisch", "Euro", "Irish Stew", "Die Harfe ist das Staatswappen Irlands."),
 ("Argentinien", "Buenos Aires", "Spanisch", "Argentinischer Peso", "Asado (Grillfleisch)", "Der Aconcagua ist mit rund 6.960 m der höchste Berg Amerikas."),
 ("Österreich", "Wien", "Deutsch", "Euro", "Wiener Schnitzel", "Rund 60 Prozent der Fläche liegen in den Alpen."),
 ("Thailand", "Bangkok", "Thai", "Baht", "Pad Thai", "Thailand wurde nie von einer europäischen Macht kolonisiert."),
 ("Kroatien", "Zagreb", "Kroatisch", "Euro", "Pašticada (Schmorbraten)", "Die Krawatte geht auf die Halstücher kroatischer Soldaten zurück."),
 ("Neuseeland", "Wellington", "Englisch, Māori und Gebärdensprache", "Neuseeland-Dollar", "Hāngī (im Erdofen gegart)", "1893 führte Neuseeland als erstes Land das Frauenwahlrecht auf nationaler Ebene ein."),
 ("Georgien", "Tiflis", "Georgisch", "Lari", "Chatschapuri (Käsebrot)", "In Georgien wird seit rund 8.000 Jahren Wein gemacht."),
 ("Finnland", "Helsinki", "Finnisch und Schwedisch", "Euro", "Karelische Piroggen", "Finnland hat rund 188.000 Seen."),
 ("Südkorea", "Seoul", "Koreanisch", "Won", "Bibimbap und Kimchi", "Das Hangeul-Alphabet wurde im 15. Jahrhundert unter König Sejong geschaffen."),
 ("Spanien", "Madrid", "Spanisch", "Euro", "Paella", "Spanien ist der größte Olivenölproduzent der Welt."),
 ("Chile", "Santiago de Chile", "Spanisch", "Chilenischer Peso", "Pastel de choclo (Maisauflauf)", "Chile ist über 4.000 km lang, im Schnitt aber nur rund 180 km breit."),
 ("Niederlande", "Amsterdam (Regierungssitz: Den Haag)", "Niederländisch", "Euro", "Stamppot", "Rund ein Viertel des Landes liegt unter dem Meeresspiegel."),
 ("Türkei", "Ankara", "Türkisch", "Türkische Lira", "Mercimek çorbası (Linsensuppe)", "Istanbul liegt auf zwei Kontinenten, in Europa und in Asien."),
 ("Kenia", "Nairobi", "Swahili und Englisch", "Kenia-Schilling", "Ugali mit Sukuma wiki", "Nairobi hat einen Nationalpark direkt am Stadtrand."),
 ("Tschechien", "Prag", "Tschechisch", "Tschechische Krone", "Svíčková (Lendenbraten in Rahmsoße)", "Tschechien hat den höchsten Bierkonsum pro Kopf der Welt."),
 ("Polen", "Warschau", "Polnisch", "Złoty", "Pierogi", "Marie Curie wurde 1867 in Warschau geboren."),
 ("Australien", "Canberra", "Englisch", "Australischer Dollar", "Meat Pie", "Das Great Barrier Reef ist das größte Korallenriffsystem der Erde."),
 ("Frankreich", "Paris", "Französisch", "Euro", "Ratatouille", "Frankreich ist das meistbesuchte Reiseland der Welt."),
]

TECH = [
 ("Tastenkürzel", "Win + V öffnet unter Windows den Verlauf der Zwischenablage – so lassen sich auch ältere Kopien wieder einfügen."),
 ("Tastenkürzel", "Win + Umschalt + S startet das Screenshot-Werkzeug für einen frei wählbaren Bereich."),
 ("Browser", "Strg + Umschalt + T öffnet den zuletzt geschlossenen Tab wieder – auch mehrmals hintereinander."),
 ("Sicherheit", "Ein Passwort-Manager wie KeePassXC oder Bitwarden erzeugt für jeden Dienst ein eigenes, starkes Passwort."),
 ("Sicherheit", "Zwei-Faktor-Anmeldung für E-Mail und Bank einschalten – am besten mit einer Authenticator-App statt SMS."),
 ("Backup", "Die 3-2-1-Regel: drei Kopien, auf zwei verschiedenen Medien, eine davon außer Haus."),
 ("Technikgeschichte", "Konrad Zuse stellte 1941 in Berlin die Z3 vor – den ersten funktionsfähigen programmgesteuerten Digitalrechner."),
 ("Tastenkürzel", "Win + Pfeiltasten dockt Fenster an den Bildschirmrand an – praktisch für zwei Fenster nebeneinander."),
 ("Tastenkürzel", "Strg + Rücktaste löscht in den meisten Programmen das ganze vorherige Wort statt nur eines Zeichens."),
 ("Heimnetz", "Ein eigenes Gast-WLAN hält Besucher- und Smart-Home-Geräte vom Hauptnetz mit PC und NAS fern."),
 ("Heimnetz", "Die Router-Firmware regelmäßig aktualisieren – viele Router können das automatisch."),
 ("Technikgeschichte", "Linus Torvalds kündigte im August 1991 ein kleines Hobby-Betriebssystem an: den Linux-Kernel."),
 ("Smartphone", "Offline-Karten in Google Maps oder OsmAnd herunterladen – hilft im Funkloch und spart Datenvolumen im Ausland."),
 ("Smartphone", "Das WLAN-Passwort lässt sich per QR-Code teilen: Android und iOS zeigen ihn in den WLAN-Einstellungen an."),
 ("Tastenkürzel", "Win + . (Punkt) öffnet das Emoji- und Sonderzeichen-Feld in jedem Textfeld."),
 ("Browser", "Strg + L springt direkt in die Adressleiste – schneller als mit der Maus."),
 ("Werkzeug", "Microsoft PowerToys ergänzt Windows um nützliche Helfer, z. B. Farbwähler, Fenster-Layouts und Text-Erkennung."),
 ("Technikgeschichte", "Am 3. Dezember 1992 wurde die erste SMS verschickt: „Merry Christmas“."),
 ("Smartphone", "Dokumente mit der Kamera-App oder der Notizen-App scannen – das ergibt saubere PDFs ohne Scanner."),
 ("Arbeitsplatz", "Die Oberkante des Monitors etwa auf Augenhöhe stellen – das entlastet Nacken und Schultern."),
 ("Tastenkürzel", "Win + L sperrt den PC sofort, wenn man den Platz verlässt."),
 ("Speicher", "Unter Windows zeigt „Einstellungen → System → Speicher“, welche Ordner den meisten Platz belegen."),
 ("Akku", "Viele Smartphones können das Laden bei 80 Prozent stoppen – das schont den Akku auf Dauer."),
 ("Technikgeschichte", "1969 wurde die erste Nachricht über das ARPANET, den Vorläufer des Internets, gesendet."),
 ("Browser", "Mit der Leseansicht (in Firefox und Edge eingebaut) werden Artikel ohne Werbung und Ablenkung angezeigt."),
 ("Tastenkürzel", "Alt + Tab wechselt zwischen offenen Fenstern; Win + Tab zeigt alle Fenster und virtuellen Desktops."),
 ("Sicherheit", "Auf haveibeenpwned.com prüfen, ob die eigene E-Mail-Adresse in bekannten Datenlecks vorkommt."),
 ("Technikgeschichte", "Die erste Website ging 1991 am CERN online – erstellt von Tim Berners-Lee."),
 ("Werkzeug", "Mit „Strg + F“ auf jeder Webseite und in fast jedem Programm nach einem Wort suchen."),
 ("Smartphone", "Im Fokus- bzw. Bitte-nicht-stören-Modus nur die wichtigsten Kontakte durchlassen – für ruhige Abende."),
 ("Technikgeschichte", "Der USB-Standard erschien 1996 und ersetzte nach und nach viele unterschiedliche Anschlüsse."),
]

BEZIEHUNG = [
 "Heute Abend gemeinsam kochen – das Handy bleibt in einem anderen Raum.",
 "Eine kurze Nachricht mitten am Tag schicken: „Ich denk an dich.“",
 "Drei Dinge nennen, die du am anderen schätzt – und zwar laut.",
 "Einen Herbstspaziergang machen und dabei nur zuhören.",
 "Das Lieblingsgetränk des anderen mitbringen, einfach so.",
 "Gemeinsam ein altes Fotoalbum oder alte Handyfotos anschauen.",
 "Eine Aufgabe übernehmen, die sonst der andere erledigt.",
 "Einen Filmabend planen, bei dem der andere den Film aussucht.",
 "Zusammen etwas Neues ausprobieren: ein Rezept, ein Spiel oder einen Ort.",
 "Beim Abendessen fragen: „Was war heute dein schönster Moment?“",
 "Einen kleinen Zettel mit einem Kompliment verstecken.",
 "Gemeinsam das nächste Wochenende planen – ohne Pflichttermine.",
 "Eine Umarmung von 20 Sekunden – bewusst länger als sonst.",
 "Zusammen frühstücken, auch wenn es nur 15 Minuten sind.",
 "Den anderen nach einem Traum oder Wunsch fragen, den er schon lange hat.",
 "Einen gemeinsamen Song aussuchen und laut mitsingen.",
 "Ein Brettspiel oder Kartenspiel hervorholen.",
 "Zusammen einen Sonnenuntergang anschauen.",
 "Danke sagen für etwas Alltägliches, das sonst selbstverständlich scheint.",
 "Ein Picknick im Wohnzimmer machen, wenn es draußen regnet.",
 "Einen Abend ohne Bildschirme verbringen.",
 "Gemeinsam ein Ziel für den Monat festlegen, das beiden Freude macht.",
 "Eine Playlist mit Liedern erstellen, die euch verbinden.",
 "Den anderen morgens mit Kaffee oder Tee im Bett überraschen.",
 "Bei einem Streit zuerst zuhören und das Gehörte in eigenen Worten wiederholen.",
 "Einen Ort besuchen, an dem ihr früher gern wart.",
 "Zusammen Sport machen – ein Lauf, eine Radtour oder Yoga.",
 "Einen Brief schreiben – ganz altmodisch, auf Papier.",
 "Gemeinsam etwas ausmisten und das Ergebnis feiern.",
 "Einen Abend lang nur Dinge tun, die der andere vorschlägt.",
 "Einfach mal fragen: „Wie geht es dir wirklich?“",
]

SPARTIPP = [
 "Deckel auf den Topf: Beim Kochen spart das viel Energie.",
 "Einkaufsliste schreiben und hungrig nicht einkaufen gehen.",
 "Abos und Verträge einmal im Jahr prüfen – ungenutzte kündigen.",
 "Standby-Geräte über eine schaltbare Steckdosenleiste ganz ausschalten.",
 "Heizung: Pro Grad weniger Raumtemperatur sinken die Heizkosten um rund sechs Prozent.",
 "Stoßlüften statt Kippfenster – mehrmals täglich 5 bis 10 Minuten.",
 "Reste einplanen: Einmal pro Woche ein „Kühlschrank-leer“-Essen kochen.",
 "Leitungswasser statt Flaschenwasser trinken.",
 "Wäsche bei 30 °C statt 60 °C waschen, wenn sie nicht stark verschmutzt ist.",
 "Preise pro Kilo oder Liter vergleichen, nicht pro Packung.",
 "Bücher, Filme und Spiele in der Stadtbibliothek ausleihen.",
 "Kaffee für unterwegs in einer eigenen Thermotasse mitnehmen.",
 "Strom- und Gastarife vergleichen – ein Wechsel ist meist in wenigen Minuten erledigt.",
 "Den Kühlschrank auf 7 °C einstellen – kälter kostet nur mehr Strom.",
 "Wasserkocher statt Herdplatte zum Wasser-Erhitzen verwenden.",
 "Gebrauchtes kaufen: Elektronik, Möbel und Kleidung gibt es oft wie neu.",
 "Die 30-Tage-Regel: Nicht-notwendige Käufe einen Monat aufschieben.",
 "Handytarif prüfen – oft reicht ein kleineres Datenvolumen.",
 "Saisonales Obst und Gemüse ist meist günstiger und schmeckt besser.",
 "Tiefkühlgemüse ist preiswert und hält lange.",
 "Duschen statt baden und einen Sparduschkopf verwenden.",
 "Geräte reparieren lassen statt neu kaufen – Repair-Cafés helfen oft kostenlos.",
 "Einmal im Monat alle Ausgaben durchgehen – das schafft Überblick.",
 "Eigene Brotzeit für die Arbeit mitnehmen.",
 "Beim Backofen die Restwärme nutzen und ihn früher ausschalten.",
 "Heizkörper nicht mit Möbeln oder Vorhängen verdecken.",
 "Rabatte der Bank- oder Kundenkarten nur nutzen, wenn man ohnehin etwas braucht.",
 "Kostenlose Freizeitangebote in der Stadt nutzen: Parks, Museumstage, Führungen.",
 "LED-Lampen statt alter Glüh- oder Halogenlampen verwenden.",
 "Automatisch einen festen Betrag am Monatsanfang zurücklegen.",
 "Doppelt kochen und die Hälfte einfrieren – spart Zeit und Geld.",
]

GESUNDHEIT = [
 "Heute ein Glas Wasser direkt nach dem Aufstehen trinken.",
 "Jede Stunde kurz aufstehen und sich strecken.",
 "Die Treppe statt des Aufzugs nehmen.",
 "Zehn Minuten Spaziergang nach dem Mittagessen.",
 "Eine Portion Gemüse mehr als sonst essen.",
 "Heute eine halbe Stunde früher ins Bett gehen.",
 "Beim Telefonieren im Gehen sprechen.",
 "Fünf Minuten bewusst atmen: 4 Sekunden ein, 6 Sekunden aus.",
 "Den Bildschirm eine Stunde vor dem Schlafen weglegen.",
 "Eine Handvoll Nüsse statt Süßigkeiten als Snack.",
 "Tageslicht tanken: 20 Minuten nach draußen gehen.",
 "Schultern kreisen lassen – zehnmal vorwärts, zehnmal rückwärts.",
 "Heute bewusst langsam essen und das Besteck zwischendurch ablegen.",
 "Eine Kniebeugen-Pause: 3 × 10 langsame Kniebeugen.",
 "Zum Einkaufen zu Fuß oder mit dem Rad fahren.",
 "Die 20-20-20-Regel für die Augen: alle 20 Minuten 20 Sekunden in 20 Fuß (6 m) Entfernung schauen.",
 "Einen Tag ohne zuckerhaltige Getränke.",
 "Abends ein kurzes Dehnprogramm für Rücken und Beine.",
 "Wasserflasche auf den Schreibtisch stellen – als Erinnerung.",
 "Zum Frühstück Haferflocken mit Obst.",
 "Ein kurzes Telefonat mit einem Freund – soziale Kontakte tun gut.",
 "Heute die Schritte zählen und 1.000 mehr als gestern schaffen.",
 "Eine Minute Planke (Unterarmstütz) – auch in Etappen.",
 "Kaffee nach 15 Uhr durch Tee ohne Koffein ersetzen.",
 "Beim Zähneputzen auf einem Bein stehen – trainiert das Gleichgewicht.",
 "Eine Mahlzeit heute komplett ohne Bildschirm essen.",
 "Das Schlafzimmer vor dem Schlafen kurz lüften.",
 "Zehn Minuten Aufräumen oder Gartenarbeit – Bewegung zählt.",
 "Eine Tasse Kräutertee statt eines Abend-Snacks.",
 "Heute bewusst eine Pause ohne Handy machen.",
 "Einen Obst- oder Gemüsetag: fünf Portionen schaffen.",
]

FILME = [
 ("Das Leben der Anderen", 2006, "Drama", "Ein Stasi-Hauptmann überwacht ein Künstlerpaar in Ost-Berlin – und beginnt zu zweifeln."),
 ("Der Club der toten Dichter", 1989, "Drama", "Ein unkonventioneller Lehrer weckt in seinen Schülern die Liebe zur Poesie."),
 ("Chihiros Reise ins Zauberland", 2001, "Animation", "Ein Mädchen gerät in eine Welt voller Geister – Meisterwerk von Studio Ghibli."),
 ("Zurück in die Zukunft", 1985, "Abenteuer, Komödie", "Marty McFly landet mit einer Zeitmaschine im Jahr 1955."),
 ("Die fabelhafte Welt der Amélie", 2001, "Komödie", "Eine schüchterne Kellnerin in Paris beschließt, anderen heimlich Gutes zu tun."),
 ("Good Bye, Lenin!", 2003, "Tragikomödie", "Ein Sohn lässt die DDR für seine kranke Mutter in der Wohnung weiterleben."),
 ("Forrest Gump", 1994, "Drama", "Ein einfacher Mann erlebt, fast zufällig, Jahrzehnte amerikanischer Geschichte."),
 ("Ziemlich beste Freunde", 2011, "Komödie", "Ein querschnittsgelähmter Millionär und sein unkonventioneller Pfleger werden Freunde."),
 ("Casablanca", 1942, "Klassiker", "Ein Barbesitzer in Marokko trifft seine alte Liebe wieder – zur Zeit des Zweiten Weltkriegs."),
 ("Das Boot", 1981, "Kriegsfilm", "Beklemmendes Porträt einer U-Boot-Besatzung im Zweiten Weltkrieg."),
 ("Toy Story", 1995, "Animation", "Spielzeuge, die lebendig werden, sobald niemand hinsieht – der erste vollständig computeranimierte Kinofilm."),
 ("Der Pate", 1972, "Drama", "Die Geschichte der Mafia-Familie Corleone."),
 ("Die Verurteilten", 1994, "Drama", "Freundschaft und Hoffnung hinter Gefängnismauern."),
 ("Lola rennt", 1998, "Thriller", "Lola hat 20 Minuten, um 100.000 Mark zu besorgen – dreimal."),
 ("Paddington 2", 2017, "Familie", "Der höfliche Bär aus Peru gerät in London in Schwierigkeiten."),
 ("Inception", 2010, "Science-Fiction", "Ein Dieb stiehlt Ideen aus Träumen – und soll nun eine einpflanzen."),
 ("Der Herr der Ringe: Die Gefährten", 2001, "Fantasy", "Ein Hobbit bricht auf, um einen gefährlichen Ring zu vernichten."),
 ("Oben", 2009, "Animation", "Ein alter Mann lässt sein Haus mit Luftballons nach Südamerika fliegen."),
 ("Das Wunder von Bern", 2003, "Drama", "Die Fußball-WM 1954 aus Sicht einer Familie im Ruhrgebiet."),
 ("Ratatouille", 2007, "Animation", "Eine Ratte mit großem Talent will in Paris Koch werden."),
 ("Die Truman Show", 1998, "Drama, Satire", "Ein Mann entdeckt, dass sein ganzes Leben eine Fernsehshow ist."),
 ("Jurassic Park", 1993, "Abenteuer", "In einem Freizeitpark leben wieder Dinosaurier – was soll schon schiefgehen?"),
 ("Soul Kitchen", 2009, "Komödie", "Ein Hamburger Restaurantbesitzer kämpft um seinen Laden."),
 ("Interstellar", 2014, "Science-Fiction", "Eine Crew sucht im All nach einer neuen Heimat für die Menschheit."),
 ("Ghostbusters", 1984, "Komödie", "Drei Wissenschaftler gründen in New York einen Geisterjäger-Service."),
 ("E.T. – Der Außerirdische", 1982, "Familie", "Ein Junge versteckt einen gestrandeten Außerirdischen."),
 ("Das Dschungelbuch", 1967, "Animation", "Mogli wächst im Dschungel bei Balu und Baghira auf."),
 ("Sing Street", 2016, "Musikfilm", "Ein Schüler im Dublin der 1980er gründet eine Band, um ein Mädchen zu beeindrucken."),
 ("Die Feuerzangenbowle", 1944, "Komödie", "Ein Schriftsteller drückt verkleidet noch einmal die Schulbank."),
 ("Arrival", 2016, "Science-Fiction", "Eine Sprachwissenschaftlerin versucht, mit Außerirdischen zu kommunizieren."),
 ("Der Name der Rose", 1986, "Krimi", "Ein Mönch untersucht rätselhafte Todesfälle in einer Abtei."),
]

SPAR_K = ['Deckel auf den Topf', 'Mit Liste einkaufen', 'Abos prüfen', 'Standby aus', 'Ein Grad weniger', 'Stoßlüften', 'Reste-Tag', 'Leitungswasser', '30 statt 60 Grad', 'Grundpreis vergleichen', 'Bibliothek nutzen', 'Eigener Kaffeebecher', 'Tarife vergleichen', 'Kühlschrank auf 7 °C', 'Wasserkocher nutzen', 'Gebraucht kaufen', '30-Tage-Regel', 'Handytarif prüfen', 'Saisonal kaufen', 'Tiefkühlgemüse', 'Duschen statt baden', 'Reparieren lassen', 'Ausgaben-Check', 'Brotzeit mitnehmen', 'Restwärme nutzen', 'Heizkörper frei', 'Rabatte mit Maß', 'Gratis-Freizeit', 'LED statt Halogen', 'Erst sparen, dann ausgeben', 'Doppelt kochen']
BEZ_K = ['Handyfrei kochen', 'Kurze Nachricht', 'Drei Dinge', 'Zuhör-Spaziergang', 'Kleine Aufmerksamkeit', 'Fotos von früher', 'Aufgabe abnehmen', 'Du wählst den Film', 'Etwas Neues', 'Schönster Moment', 'Versteckter Zettel', 'Freies Wochenende', 'Lange Umarmung', 'Gemeinsames Frühstück', 'Nach Träumen fragen', 'Euer Song', 'Spieleabend', 'Sonnenuntergang', 'Danke sagen', 'Wohnzimmer-Picknick', 'Bildschirmfreier Abend', 'Gemeinsames Monatsziel', 'Eure Playlist', 'Kaffee ans Bett', 'Erst zuhören', 'Alter Lieblingsort', 'Zusammen Sport', 'Ein echter Brief', 'Gemeinsam ausmisten', 'Dein Abend, meine Wahl', 'Wie geht es dir?']
GES_K = ['Wasser zuerst', 'Stündlich strecken', 'Treppe statt Aufzug', 'Verdauungsspaziergang', 'Mehr Gemüse', 'Früher ins Bett', 'Telefonieren im Gehen', 'Ruhig atmen', 'Bildschirm weg', 'Nüsse statt Süßes', 'Tageslicht tanken', 'Schultern kreisen', 'Langsam essen', 'Kniebeugen-Pause', 'Zu Fuß einkaufen', '20-20-20-Regel', 'Ohne Zuckergetränke', 'Abends dehnen', 'Wasser in Sichtweite', 'Haferflocken-Frühstück', 'Freunde anrufen', '1.000 Schritte mehr', 'Eine Minute Planke', 'Kein Koffein am Abend', 'Balance beim Zähneputzen', 'Essen ohne Bildschirm', 'Vor dem Schlafen lüften', 'Aktiv aufräumen', 'Tee statt Snack', 'Handypause', 'Fünf am Tag']

lists = [RAETSEL, MITMACHEN, QUIZ, WITZE, WORTE, SPRICHWOERTER, REZEPTE, LAENDER, TECH, BEZIEHUNG, SPARTIPP, GESUNDHEIT, FILME]
for l in lists:
    assert len(l) == 31, (len(l), l[0])

days = []
for i in range(31):
    d = START + datetime.timedelta(days=i)
    r, mi, qz, w, wo, sp, re_, la, te, be, sa, ge, fi = (l[i] for l in lists)
    days.append({
        "datum": d.isoformat(),
        "raetsel": {"frage": r[0], "loesung": r[1], "antwort": mi[0], "falsch": mi[1], "tipps": mi[2]},
        "quiz": [{"frage": q[0], "antwort": q[1], "falsch": q[2], "erklaerung": q[3]} for q in qz],
        "witz": w,
        "wort": {"wort": wo[0], "bedeutung": wo[1], "herkunft": wo[2]},
        "sprichwort": sp,
        "rezept": {"name": re_[0], "minuten": re_[1], "vegetarisch": re_[2], "zutaten": re_[3], "zubereitung": re_[4]},
        "land": {"name": la[0], "hauptstadt": la[1], "sprache": la[2], "waehrung": la[3], "gericht": la[4], "fakt": la[5]},
        "tech": {"kategorie": te[0], "text": te[1]},
        "beziehung": {"kurz": BEZ_K[i], "text": be},
        "spartipp": {"kurz": SPAR_K[i], "text": sa},
        "gesundheit": {"kurz": GES_K[i], "text": ge},
        "film": {"titel": fi[0], "jahr": fi[1], "genre": fi[2], "text": fi[3]},
    })

out = pathlib.Path(__file__).resolve().parent.parent / "services" / "daten" / "daily.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps({"version": 1, "von": days[0]["datum"], "bis": days[-1]["datum"], "tage": days}, ensure_ascii=False, indent=1), encoding="utf-8")
print("geschrieben:", out, len(days), "Tage", days[0]["datum"], "bis", days[-1]["datum"])
