# Quiz zum Mitmachen (Phase 3, App 0.52.0): je Tag 5 Fragen von leicht bis schwer, je eine richtige und 3 falsche Antworten
# und eine kurze Erklärung. Wird von content_2026_10.py eingelesen. Nur zeitlose Fakten (Roger prüft vollständig, Entscheidung 0a/15).
QUIZ = [
 [  # 26.9.
  ("Wie viele Beine hat eine Spinne?", "8", ["6", "10", "12"], "Spinnen sind Spinnentiere mit acht Beinen – Insekten haben sechs."),
  ("Welche Farbe entsteht, wenn man blaue und gelbe Malfarbe mischt?", "Grün", ["Lila", "Orange", "Braun"], "Blau und Gelb ergeben beim Mischen von Malfarben Grün."),
  ("Wie heißt die Hauptstadt von Kanada?", "Ottawa", ["Toronto", "Montreal", "Vancouver"], "Toronto ist die größte Stadt Kanadas, Hauptstadt ist aber Ottawa."),
  ("Wer malte die „Mona Lisa“?", "Leonardo da Vinci", ["Michelangelo", "Raffael", "Rembrandt"], "Leonardo malte sie Anfang des 16. Jahrhunderts; heute hängt sie im Louvre in Paris."),
  ("Welches chemische Element hat das Zeichen „Fe“?", "Eisen", ["Fluor", "Fermium", "Phosphor"], "„Fe“ kommt vom lateinischen „ferrum“ für Eisen."),
 ],
 [  # 27.9.
  ("Wie viele Minuten hat eine Stunde?", "60", ["100", "30", "90"], "Eine Stunde hat 60 Minuten, eine Minute 60 Sekunden."),
  ("Welches ist das größte heute lebende Tier?", "Blauwal", ["Afrikanischer Elefant", "Pottwal", "Walhai"], "Blauwale werden bis zu etwa 30 Meter lang."),
  ("In welchem Land stehen die Pyramiden von Gizeh?", "Ägypten", ["Mexiko", "Sudan", "Marokko"], "Gizeh liegt am Rand von Kairo."),
  ("Welcher Planet ist der Sonne am nächsten?", "Merkur", ["Venus", "Mars", "Erde"], "Merkur ist der innerste und kleinste Planet unseres Sonnensystems."),
  ("Aus welchem Land stammte der Komponist Frédéric Chopin?", "Polen", ["Frankreich", "Österreich", "Ungarn"], "Chopin wurde 1810 bei Warschau geboren und lebte später in Paris."),
 ],
 [  # 28.9.
  ("Was fressen Große Pandas hauptsächlich?", "Bambus", ["Eukalyptus", "Fisch", "Gras"], "Große Pandas fressen fast nur Bambus – Eukalyptus ist das Futter der Koalas."),
  ("Welcher Fluss fließt durch Wien?", "Donau", ["Rhein", "Elbe", "Moldau"], "Die Donau fließt durch vier Hauptstädte: Wien, Bratislava, Budapest und Belgrad."),
  ("Wer schrieb „Faust“?", "Johann Wolfgang von Goethe", ["Friedrich Schiller", "Heinrich Heine", "Thomas Mann"], "Goethe arbeitete fast sein ganzes Leben an „Faust“."),
  ("Wie heißt der höchste Berg Deutschlands?", "Zugspitze", ["Watzmann", "Feldberg", "Brocken"], "Die Zugspitze im Wettersteingebirge ist 2962 Meter hoch."),
  ("Was misst die Einheit „Hertz“?", "Frequenz", ["Lautstärke", "Spannung", "Leistung"], "Ein Hertz ist eine Schwingung pro Sekunde – benannt nach Heinrich Hertz."),
 ],
 [  # 29.9.
  ("Welches dieser Tiere ist ein Säugetier?", "Delfin", ["Hai", "Thunfisch", "Seepferdchen"], "Delfine atmen Luft und säugen ihre Jungen."),
  ("Wie viele Ecken hat ein Würfel?", "8", ["6", "12", "4"], "Ein Würfel hat 6 Flächen, 12 Kanten und 8 Ecken."),
  ("In welcher Stadt steht das Brandenburger Tor?", "Berlin", ["Potsdam", "Brandenburg an der Havel", "Hamburg"], "Das Brandenburger Tor steht in Berlin am Pariser Platz."),
  ("Welches Gas nehmen Pflanzen für die Fotosynthese auf?", "Kohlendioxid", ["Sauerstoff", "Stickstoff", "Wasserstoff"], "Pflanzen nehmen Kohlendioxid auf und geben Sauerstoff ab."),
  ("In welchem Jahr fiel die Berliner Mauer?", "1989", ["1990", "1987", "1991"], "Die Mauer fiel am 9. November 1989; die Einheit folgte am 3. Oktober 1990."),
 ],
 [  # 30.9.
  ("Welche Jahreszeit beginnt auf der Nordhalbkugel im Dezember?", "Winter", ["Herbst", "Frühling", "Sommer"], "Der astronomische Winter beginnt um den 21. Dezember."),
  ("Welches Musikinstrument hat meist 88 Tasten?", "Klavier", ["Orgel", "Akkordeon", "Cembalo"], "Ein modernes Klavier hat 88 Tasten: 52 weiße und 36 schwarze."),
  ("Wie heißt die Währung Japans?", "Yen", ["Won", "Yuan", "Baht"], "Der Won ist die Währung Koreas, der Yuan die Chinas, der Baht die Thailands."),
  ("Welcher Vogel kann sogar rückwärts fliegen?", "Kolibri", ["Mauersegler", "Eisvogel", "Turmfalke"], "Kolibris können in der Luft stehen und auch rückwärts fliegen."),
  ("Wie viele Knochen hat ein erwachsener Mensch ungefähr?", "206", ["106", "306", "256"], "Ein Erwachsener hat etwa 206 Knochen; bei Babys sind es mehr, einige wachsen später zusammen."),
 ],
 [  # 1.10.
  ("Welche Form hat ein Stoppschild?", "Achteck", ["Dreieck", "Kreis", "Quadrat"], "Das Stoppschild ist ein rotes Achteck – fast überall auf der Welt."),
  ("Welches Land hat die Form eines Stiefels?", "Italien", ["Griechenland", "Spanien", "Portugal"], "Italien sieht auf der Karte aus wie ein Stiefel."),
  ("Wie heißt das größte Organ des Menschen?", "Die Haut", ["Die Leber", "Die Lunge", "Das Gehirn"], "Die Haut eines Erwachsenen ist rund 1,5 bis 2 Quadratmeter groß."),
  ("Wer entwickelte die Relativitätstheorie?", "Albert Einstein", ["Isaac Newton", "Max Planck", "Niels Bohr"], "Einstein veröffentlichte 1905 die spezielle und 1915 die allgemeine Relativitätstheorie."),
  ("Wie heißt die Hauptstadt von Australien?", "Canberra", ["Sydney", "Melbourne", "Perth"], "Canberra wurde als Kompromiss zwischen Sydney und Melbourne zur Hauptstadt."),
 ],
 [  # 2.10.
  ("Welches Obst ist gelb und krumm?", "Banane", ["Zitrone", "Birne", "Mango"], "Bananen wachsen in Büscheln und krümmen sich zum Licht."),
  ("Wie viele Spieler einer Mannschaft stehen beim Hallenvolleyball auf dem Feld?", "6", ["5", "7", "8"], "Beim Hallenvolleyball spielen sechs gegen sechs, beim Beachvolleyball zwei gegen zwei."),
  ("Welcher Ozean ist der größte?", "Pazifik", ["Atlantik", "Indischer Ozean", "Arktischer Ozean"], "Der Pazifik ist größer als alle Landflächen der Erde zusammen."),
  ("Wer komponierte die Neunte Sinfonie mit der „Ode an die Freude“?", "Ludwig van Beethoven", ["Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"], "Beethoven war bei der Uraufführung 1824 schon fast taub."),
  ("Was bedeutet „carpe diem“?", "Nutze den Tag", ["Hüte dich vor dem Tag", "Der Tag ist vorbei", "Bete am Tag"], "Der lateinische Spruch stammt vom römischen Dichter Horaz."),
 ],
 [  # 3.10.
  ("Welches Tier gilt als „König der Tiere“?", "Löwe", ["Tiger", "Adler", "Elefant"], "In Fabeln und Märchen ist der Löwe der König der Tiere."),
  ("Bei wie viel Grad Celsius gefriert Wasser?", "0 °C", ["−10 °C", "4 °C", "100 °C"], "Bei normalem Luftdruck gefriert Wasser bei 0 °C und siedet bei 100 °C."),
  ("Welches ist das flächenmäßig größte deutsche Bundesland?", "Bayern", ["Niedersachsen", "Baden-Württemberg", "Nordrhein-Westfalen"], "Bayern ist das größte Bundesland, Niedersachsen das zweitgrößte."),
  ("Wer betrat als erster Mensch den Mond?", "Neil Armstrong", ["Buzz Aldrin", "Juri Gagarin", "Michael Collins"], "Armstrong betrat im Juli 1969 als Erster den Mond, Aldrin folgte kurz danach."),
  ("Wie viele Herzen hat ein Krake?", "3", ["1", "2", "4"], "Zwei Herzen pumpen das Blut durch die Kiemen, eines durch den Körper."),
 ],
 [  # 4.10.
  ("Welche Farbe hat ein Smaragd?", "Grün", ["Rot", "Blau", "Gelb"], "Smaragde sind grüne Edelsteine – Rubine sind rot, Saphire meist blau."),
  ("Wie viele Saiten hat eine gewöhnliche Gitarre?", "6", ["4", "5", "8"], "Eine Gitarre hat meist sechs Saiten, ein E-Bass meist vier."),
  ("Wie heißt die Hauptstadt von Spanien?", "Madrid", ["Barcelona", "Sevilla", "Valencia"], "Madrid liegt fast genau in der Mitte Spaniens."),
  ("Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?", "Vitamin D", ["Vitamin C", "Vitamin A", "Vitamin B12"], "Mit UV-Licht bildet die Haut Vitamin D – wichtig für die Knochen."),
  ("Wie heißt die Lehre von den Pilzen?", "Mykologie", ["Ornithologie", "Botanik", "Entomologie"], "Griechisch „mýkēs“ heißt Pilz; Ornithologie ist die Vogelkunde, Entomologie die Insektenkunde."),
 ],
 [  # 5.10.
  ("Welche Zahl steht auf dem Zifferblatt einer Uhr ganz oben?", "12", ["1", "6", "0"], "Oben steht die 12, unten die 6."),
  ("Welches Tier ist das Wappentier Deutschlands?", "Adler", ["Löwe", "Bär", "Hirsch"], "Der Bundesadler ist das Wappentier der Bundesrepublik."),
  ("In welcher Stadt steht der Schiefe Turm?", "Pisa", ["Rom", "Florenz", "Venedig"], "Der Glockenturm des Doms von Pisa neigte sich schon während des Baus."),
  ("Woraus wird Glas hauptsächlich hergestellt?", "Quarzsand", ["Ton", "Salz", "Holz"], "Glas entsteht vor allem aus geschmolzenem Quarzsand, dazu kommen Soda und Kalk."),
  ("Welche Sprache hat weltweit die meisten Muttersprachler?", "Chinesisch (Mandarin)", ["Englisch", "Spanisch", "Hindi"], "Englisch wird häufiger gesprochen, wenn man alle mitzählt, die es als Zweitsprache sprechen."),
 ],
 [  # 6.10.
  ("Wie nennt man ein junges Pferd?", "Fohlen", ["Kalb", "Lamm", "Ferkel"], "Ein Kalb ist ein junges Rind, ein Lamm ein junges Schaf, ein Ferkel ein junges Schwein."),
  ("Wie viel Grad hat ein rechter Winkel?", "90", ["45", "180", "100"], "Ein rechter Winkel hat 90 Grad, ein gestreckter 180 Grad."),
  ("Welche dieser Inseln gehört zu Deutschland?", "Rügen", ["Bornholm", "Texel", "Gotland"], "Bornholm gehört zu Dänemark, Texel zu den Niederlanden, Gotland zu Schweden."),
  ("Wer erfand in Europa den Buchdruck mit beweglichen Lettern?", "Johannes Gutenberg", ["Martin Luther", "Albrecht Dürer", "Leonardo da Vinci"], "Gutenberg druckte um 1450 in Mainz – seine Bibel ist berühmt."),
  ("Welches Metall ist bei Zimmertemperatur flüssig?", "Quecksilber", ["Blei", "Zinn", "Aluminium"], "Quecksilber ist das einzige Metall, das bei üblicher Zimmertemperatur (um 20 °C) flüssig ist."),
 ],
 [  # 7.10.
  ("Was sammeln Bienen aus Blüten?", "Nektar", ["Honig", "Wachs", "Harz"], "Aus dem Nektar machen Bienen im Stock Honig."),
  ("Wie viele Stunden hat ein Tag?", "24", ["12", "36", "20"], "Ein Tag hat 24 Stunden – so lange dauert ungefähr eine Drehung der Erde."),
  ("Welches ist das kleinste deutsche Bundesland?", "Bremen", ["Saarland", "Hamburg", "Berlin"], "Bremen ist mit Bremerhaven das kleinste Bundesland."),
  ("Welcher Planet hat die auffälligsten Ringe?", "Saturn", ["Jupiter", "Uranus", "Neptun"], "Alle großen Gasplaneten haben Ringe, die des Saturn sind aber am hellsten."),
  ("Aus welcher Sprache stammt das Wort „Kindergarten“, das viele Sprachen übernommen haben?", "Deutsch", ["Englisch", "Niederländisch", "Dänisch"], "Friedrich Fröbel prägte den Begriff 1840; heute sagt man ihn auch im Englischen."),
 ],
 [  # 8.10.
  ("Welches Tier hat einen Rüssel?", "Elefant", ["Nashorn", "Nilpferd", "Giraffe"], "Mit dem Rüssel greift, trinkt und riecht der Elefant."),
  ("Wie heißt das Ergebnis einer Addition?", "Summe", ["Produkt", "Differenz", "Quotient"], "Summe beim Addieren, Differenz beim Subtrahieren, Produkt beim Multiplizieren, Quotient beim Dividieren."),
  ("In welcher Stadt sitzen Regierung und Parlament der Schweiz?", "Bern", ["Zürich", "Genf", "Basel"], "Bern ist die Bundesstadt der Schweiz – Zürich ist die größte Stadt."),
  ("Welche Blutgruppe gilt als Universalspender für rote Blutkörperchen?", "0 negativ", ["AB positiv", "A positiv", "B negativ"], "0 negativ kann im Notfall fast allen gegeben werden; AB positiv gilt als Universalempfänger."),
  ("Wer schrieb das Drama „Die Räuber“?", "Friedrich Schiller", ["Johann Wolfgang von Goethe", "Gotthold Ephraim Lessing", "Heinrich von Kleist"], "Schiller schrieb „Die Räuber“ als junger Mann; die Uraufführung war 1782 in Mannheim."),
 ],
 [  # 9.10.
  ("Welches Tier baut Dämme in Flüssen?", "Biber", ["Fischotter", "Nutria", "Waschbär"], "Biber stauen Bäche mit Ästen und Schlamm auf."),
  ("Um welchen Tag herum ist auf der Nordhalbkugel die längste Nacht?", "21. Dezember", ["21. Juni", "1. Januar", "21. März"], "Zur Wintersonnenwende um den 21. Dezember ist die Nacht am längsten."),
  ("Welches Land der EU hat die meisten Einwohner?", "Deutschland", ["Frankreich", "Italien", "Spanien"], "Deutschland hat gut 80 Millionen Einwohner, Frankreich folgt auf Platz zwei."),
  ("Wer sammelte das Märchen „Hänsel und Gretel“?", "Die Brüder Grimm", ["Hans Christian Andersen", "Wilhelm Hauff", "Charles Perrault"], "Jacob und Wilhelm Grimm gaben ab 1812 ihre „Kinder- und Hausmärchen“ heraus."),
  ("Wie viel der Erdoberfläche ist ungefähr mit Wasser bedeckt?", "etwa 71 %", ["etwa 50 %", "etwa 85 %", "etwa 60 %"], "Rund 71 Prozent der Erdoberfläche sind Wasser – fast alles davon Meer."),
 ],
 [  # 10.10.
  ("Welches dieser Fahrzeuge fährt auf Schienen?", "Straßenbahn", ["Bus", "Lastwagen", "Taxi"], "Straßenbahnen fahren auf Schienen, meist mitten in der Stadt."),
  ("Was zeigt ein Thermometer an?", "Temperatur", ["Luftdruck", "Luftfeuchtigkeit", "Windstärke"], "Griechisch „thermós“ heißt warm."),
  ("Welches Meer liegt im Norden Deutschlands neben der Ostsee?", "Nordsee", ["Mittelmeer", "Schwarzes Meer", "Barentssee"], "Deutschland grenzt an Nordsee und Ostsee."),
  ("Was ist die Hauptzutat von Guacamole?", "Avocado", ["Gurke", "Erbsen", "Limette"], "Guacamole ist ein mexikanischer Dip aus Avocado, oft mit Limette und Zwiebel."),
  ("In welchem Jahr begann der Erste Weltkrieg?", "1914", ["1912", "1916", "1918"], "Der Erste Weltkrieg dauerte von 1914 bis 1918."),
 ],
 [  # 11.10.
  ("Was hat ein Zebra auf dem Fell?", "Streifen", ["Punkte", "Schuppen", "Federn"], "Jedes Zebra hat ein eigenes Streifenmuster – wie ein Fingerabdruck."),
  ("Wie viele Nullen hat eine Million?", "6", ["5", "7", "9"], "Eine Million ist 1.000.000 – eine Milliarde hat neun Nullen."),
  ("Wie heißt die Hauptstadt von Portugal?", "Lissabon", ["Porto", "Faro", "Coimbra"], "Lissabon liegt an der Mündung des Tejo in den Atlantik."),
  ("Welches dieser Tiere ist ein Beuteltier?", "Känguru", ["Faultier", "Gürteltier", "Ameisenbär"], "Kängurus tragen ihre Jungen im Beutel am Bauch."),
  ("Wie heißt die Angst vor Spinnen?", "Arachnophobie", ["Klaustrophobie", "Akrophobie", "Agoraphobie"], "Klaustrophobie ist Angst vor engen Räumen, Akrophobie Höhenangst."),
 ],
 [  # 12.10.
  ("Welches dieser Tiere hält Winterschlaf?", "Igel", ["Reh", "Eichhörnchen", "Fuchs"], "Igel schlafen den ganzen Winter; Eichhörnchen halten nur Winterruhe und wachen oft auf."),
  ("Welche Farbe hat der Kreis auf der Flagge Japans?", "Rot", ["Gelb", "Blau", "Schwarz"], "Der rote Kreis auf Weiß steht für die Sonne."),
  ("Welcher Kontinent ist der größte?", "Asien", ["Afrika", "Nordamerika", "Europa"], "Asien ist der größte Kontinent – nach Fläche und nach Einwohnern."),
  ("Wie viele Spieler einer Mannschaft stehen beim Basketball auf dem Feld?", "5", ["6", "7", "4"], "Beim Basketball spielen fünf gegen fünf."),
  ("Wer gilt als Begründer der Evolutionstheorie durch natürliche Auslese?", "Charles Darwin", ["Gregor Mendel", "Alexander von Humboldt", "Carl von Linné"], "Darwin veröffentlichte 1859 „Über die Entstehung der Arten“."),
 ],
 [  # 13.10.
  ("An welchem Fest werden traditionell Eier bemalt?", "Ostern", ["Weihnachten", "Pfingsten", "Erntedank"], "Bemalte Eier gehören bei uns zum Osterfest."),
  ("Welches ist das schnellste Landtier?", "Gepard", ["Löwe", "Antilope", "Strauß"], "Geparde erreichen im Sprint über 100 km/h – aber nur kurz."),
  ("Welches dieser Länder grenzt nicht an Deutschland?", "Italien", ["Österreich", "Polen", "Luxemburg"], "Zwischen Deutschland und Italien liegen Österreich und die Schweiz."),
  ("Was ist H₂O?", "Wasser", ["Wasserstoffperoxid", "Kochsalz", "Sauerstoff"], "Ein Wassermolekül besteht aus zwei Wasserstoffatomen und einem Sauerstoffatom."),
  ("Wie heißt die Hauptstadt der Türkei?", "Ankara", ["Istanbul", "Izmir", "Antalya"], "Istanbul ist die größte Stadt, Hauptstadt ist seit 1923 Ankara."),
 ],
 [  # 14.10.
  ("Welches heimische Wildtier ist mit dem Hund verwandt und hat meist rotes Fell?", "Fuchs", ["Dachs", "Marder", "Luchs"], "Der Rotfuchs gehört zur Familie der Hunde."),
  ("Wie viele Minuten dauert ein Fußballspiel ohne Nachspielzeit?", "90", ["80", "100", "120"], "Zwei Halbzeiten zu je 45 Minuten."),
  ("In welchem Land liegt Machu Picchu?", "Peru", ["Mexiko", "Bolivien", "Chile"], "Die Inka-Stadt liegt hoch in den Anden Perus."),
  ("Wie heißt die Wissenschaft von den Sternen und dem Weltall?", "Astronomie", ["Astrologie", "Geologie", "Meteorologie"], "Astrologie ist Sterndeutung und keine Wissenschaft."),
  ("Welcher Komponist wurde in Salzburg geboren?", "Wolfgang Amadeus Mozart", ["Joseph Haydn", "Franz Schubert", "Johann Strauss"], "Mozart wurde 1756 in Salzburg geboren."),
 ],
 [  # 15.10.
  ("Welche Jahreszeit folgt auf den Sommer?", "Herbst", ["Winter", "Frühling", "Regenzeit"], "Auf den Sommer folgt der Herbst – bei uns beginnt er um den 22. September."),
  ("Wie heißt der Stern im Mittelpunkt unseres Sonnensystems?", "Sonne", ["Polarstern", "Sirius", "Mond"], "Alle Planeten unseres Sonnensystems kreisen um die Sonne."),
  ("Wie heißt die Hauptstadt von Sachsen?", "Dresden", ["Leipzig", "Chemnitz", "Magdeburg"], "Leipzig ist die größte Stadt Sachsens, Hauptstadt ist Dresden."),
  ("Was misst ein Barometer?", "Luftdruck", ["Temperatur", "Windgeschwindigkeit", "Luftfeuchtigkeit"], "Fällt der Luftdruck, kommt oft schlechtes Wetter."),
  ("Wie heißt das kleinste Land der Welt?", "Vatikanstadt", ["Monaco", "San Marino", "Liechtenstein"], "Die Vatikanstadt in Rom ist nicht einmal einen halben Quadratkilometer groß."),
 ],
 [  # 16.10.
  ("Welche Farbe haben Feuerwehrautos in Deutschland meistens?", "Rot", ["Gelb", "Blau", "Grün"], "Feuerwehrfahrzeuge sind bei uns meist rot."),
  ("Wie viele Tage hat ein Schaltjahr?", "366", ["365", "364", "367"], "Im Schaltjahr hat der Februar 29 Tage."),
  ("Welches dieser Tiere ist kein Vogel?", "Fledermaus", ["Pinguin", "Strauß", "Kiwi"], "Fledermäuse sind Säugetiere – die einzigen, die richtig fliegen können."),
  ("Wer malte „Die Sternennacht“?", "Vincent van Gogh", ["Claude Monet", "Paul Cézanne", "Edvard Munch"], "Van Gogh malte das Bild 1889 in Südfrankreich."),
  ("Welcher Planet ist der größte unseres Sonnensystems?", "Jupiter", ["Saturn", "Neptun", "Uranus"], "In den Jupiter würde die Erde mehr als tausendmal hineinpassen."),
 ],
 [  # 17.10.
  ("Welches Tier hat lange Ohren und hoppelt über das Feld?", "Hase", ["Hamster", "Igel", "Meerschweinchen"], "Feldhasen haben lange Ohren und kräftige Hinterbeine."),
  ("Wie heißt die Hauptstadt von Österreich?", "Wien", ["Salzburg", "Graz", "Innsbruck"], "Wien liegt an der Donau."),
  ("Welches Gemüse lässt beim Schneiden oft die Augen tränen?", "Zwiebel", ["Karotte", "Gurke", "Paprika"], "Beim Schneiden setzt die Zwiebel einen Stoff frei, der die Augen reizt."),
  ("Auf welchem Kontinent liegt der Südpol?", "Antarktika", ["Arktis", "Australien", "Grönland"], "Die Arktis am Nordpol ist kein Kontinent, sondern ein vereistes Meer."),
  ("In welchem Jahr veröffentlichte Martin Luther seine 95 Thesen?", "1517", ["1492", "1521", "1555"], "Der 31. Oktober 1517 gilt als Beginn der Reformation."),
 ],
 [  # 18.10.
  ("Wie nennt man einen jungen Hund?", "Welpe", ["Kitz", "Küken", "Frischling"], "Ein Kitz ist ein junges Reh, ein Frischling ein junges Wildschwein."),
  ("Welche Farbe entsteht aus Rot und Weiß?", "Rosa", ["Lila", "Orange", "Braun"], "Rot mit Weiß aufgehellt ergibt Rosa."),
  ("Wie heißt die Hauptstadt von Norwegen?", "Oslo", ["Bergen", "Stockholm", "Helsinki"], "Stockholm ist die Hauptstadt Schwedens, Helsinki die Finnlands."),
  ("Welches Gas ist in der Luft am häufigsten?", "Stickstoff", ["Sauerstoff", "Kohlendioxid", "Argon"], "Luft besteht zu etwa 78 Prozent aus Stickstoff und zu etwa 21 Prozent aus Sauerstoff."),
  ("Wer schrieb „Romeo und Julia“?", "William Shakespeare", ["Christopher Marlowe", "Charles Dickens", "Molière"], "Shakespeare schrieb die Tragödie Ende des 16. Jahrhunderts."),
 ],
 [  # 19.10.
  ("Welches Tier spinnt ein Netz, um Beute zu fangen?", "Spinne", ["Raupe", "Ameise", "Biene"], "Die Fäden des Netzes kommen aus den Spinndrüsen am Hinterleib."),
  ("Wie viele Zentimeter hat ein Meter?", "100", ["10", "1000", "60"], "Ein Meter hat 100 Zentimeter oder 1000 Millimeter."),
  ("In welcher Stadt steht die Freiheitsstatue?", "New York", ["Washington", "Boston", "Philadelphia"], "Die Statue war ein Geschenk Frankreichs und steht seit 1886 vor New York."),
  ("Welche Sportart wird beim Turnier in Wimbledon gespielt?", "Tennis", ["Golf", "Cricket", "Polo"], "Wimbledon in London ist das älteste Tennisturnier der Welt."),
  ("Wie lautet das Fachwort für Tiere, die nur Pflanzen fressen?", "Herbivoren", ["Karnivoren", "Omnivoren", "Insektivoren"], "Karnivoren fressen Fleisch, Omnivoren alles."),
 ],
 [  # 20.10.
  ("Womit schreibt man traditionell auf eine Schultafel?", "Kreide", ["Tinte", "Radiergummi", "Kleber"], "Tafelkreide besteht meist aus Gips oder Kalk."),
  ("Wie viele Felder hat ein Schachbrett?", "64", ["32", "81", "100"], "Ein Schachbrett hat 8 mal 8 Felder."),
  ("Welches Tier ist das Zeichen der Naturschutzorganisation WWF?", "Großer Panda", ["Eisbär", "Tiger", "Gorilla"], "Der Panda ist seit der Gründung 1961 im Zeichen des WWF."),
  ("Welcher Fluss fließt durch Paris?", "Seine", ["Loire", "Rhône", "Garonne"], "Die Seine fließt durch Paris und mündet bei Le Havre in den Ärmelkanal."),
  ("Was ist der Hauptbestandteil von Erdgas?", "Methan", ["Propan", "Butan", "Ethanol"], "Erdgas besteht größtenteils aus Methan."),
 ],
 [  # 21.10.
  ("Was ist das Gegenteil von „heiß“?", "Kalt", ["Warm", "Lauwarm", "Feucht"], "Heiß und kalt sind Gegensätze, lauwarm liegt dazwischen."),
  ("Wie heißt die Wohnung eines Bibers?", "Biberburg", ["Kobel", "Horst", "Kessel"], "Ein Kobel ist das Nest des Eichhörnchens, ein Horst das eines Greifvogels, der Kessel die Wohnhöhle im Fuchs- oder Dachsbau. Manche Biber wohnen statt in einer Burg in einem Erdbau am Ufer."),
  ("Wie heißt die Hauptstadt von Griechenland?", "Athen", ["Thessaloniki", "Sparta", "Korinth"], "Über Athen thront die Akropolis."),
  ("Welches Tier kann seine Farbe wechseln?", "Chamäleon", ["Krokodil", "Schildkröte", "Salamander"], "Chamäleons ändern ihre Farbe je nach Stimmung, Temperatur und Licht."),
  ("Wer entdeckte das Penicillin?", "Alexander Fleming", ["Louis Pasteur", "Robert Koch", "Marie Curie"], "Fleming entdeckte das Penicillin 1928 durch einen Schimmelpilz auf einer Bakterienkultur in einer Petrischale."),
 ],
 [  # 22.10.
  ("Welches dieser Tiere lebt im Wasser und hat Flossen?", "Forelle", ["Frosch", "Ente", "Biber"], "Forellen sind Fische und atmen mit Kiemen."),
  ("Welche Form hat die Erde ungefähr?", "Kugel", ["Scheibe", "Würfel", "Ring"], "Die Erde ist fast eine Kugel, an den Polen etwas abgeplattet."),
  ("Welche dieser Städte liegt an der Elbe?", "Hamburg", ["Köln", "München", "Frankfurt am Main"], "Köln liegt am Rhein, München an der Isar, Frankfurt am Main."),
  ("Von welchem Tier stammt Seide?", "Seidenraupe", ["Spinne", "Schaf", "Biene"], "Die Raupe des Seidenspinners spinnt einen Kokon aus Seidenfaden."),
  ("Welches Land richtete 1896 die ersten Olympischen Spiele der Neuzeit aus?", "Griechenland", ["Frankreich", "Großbritannien", "USA"], "Die ersten Spiele der Neuzeit fanden 1896 in Athen statt."),
 ],
 [  # 23.10.
  ("Welches Wetter braucht man für einen Regenbogen?", "Sonne und Regen", ["Schnee und Wind", "Nebel und Frost", "Gewitter in der Nacht"], "Sonnenlicht wird in Regentropfen gebrochen – die Sonne steht dabei hinter dir."),
  ("Was ist länger: ein Kilometer oder eine Meile?", "Eine Meile", ["Ein Kilometer", "Beide gleich lang", "Kommt aufs Land an"], "Eine Meile ist etwa 1,6 Kilometer lang."),
  ("Wie heißt die Hauptstadt von Irland?", "Dublin", ["Cork", "Belfast", "Galway"], "Belfast ist die Hauptstadt von Nordirland, das zum Vereinigten Königreich gehört."),
  ("Welches Organ reinigt das Blut und bildet Urin?", "Niere", ["Leber", "Milz", "Lunge"], "Die Nieren filtern jeden Tag viele hundert Liter Blut."),
  ("Wer schrieb „Die Verwandlung“, in der Gregor Samsa zu einem Ungeziefer wird?", "Franz Kafka", ["Thomas Mann", "Hermann Hesse", "Robert Musil"], "Kafkas Erzählung erschien 1915 – meist stellt man sich das Ungeziefer als Käfer vor."),
 ],
 [  # 24.10.
  ("Welches dieser Tiere hat einen Panzer?", "Schildkröte", ["Frosch", "Eidechse", "Schnecke"], "Der Panzer der Schildkröte ist mit ihrem Skelett verwachsen."),
  ("Wie viele Farben hat ein Regenbogen nach der üblichen Zählung?", "7", ["5", "6", "9"], "Rot, Orange, Gelb, Grün, Blau, Indigo und Violett – so zählte schon Isaac Newton."),
  ("Wie heißt der höchste Berg der Welt?", "Mount Everest", ["K2", "Kilimandscharo", "Mont Blanc"], "Der Mount Everest im Himalaya ist rund 8849 Meter hoch."),
  ("In welcher Einheit misst man elektrische Spannung?", "Volt", ["Ampere", "Watt", "Ohm"], "Ampere ist die Stromstärke, Watt die Leistung, Ohm der Widerstand."),
  ("In welcher Stadt wurde Ludwig van Beethoven geboren?", "Bonn", ["Wien", "Köln", "Salzburg"], "Beethoven wurde 1770 in Bonn geboren und lebte später in Wien."),
 ],
 [  # 25.10.
  ("Welche Frucht wächst an einer Palme und hat eine harte Schale?", "Kokosnuss", ["Walnuss", "Mango", "Ananas"], "Kokosnüsse wachsen an Kokospalmen, oft an tropischen Stränden."),
  ("Wie viele Wochen hat ein Jahr ungefähr?", "52", ["48", "50", "56"], "Ein Jahr hat 52 Wochen und ein oder zwei Tage."),
  ("Wie heißt die Hauptstadt von Polen?", "Warschau", ["Krakau", "Danzig", "Breslau"], "Krakau war bis um 1600 Hauptstadt, seitdem ist es Warschau."),
  ("Welches ist das größte Landtier?", "Afrikanischer Elefant", ["Nashorn", "Flusspferd", "Giraffe"], "Giraffen sind die höchsten Tiere, Afrikanische Elefanten die schwersten an Land."),
  ("Wie heißt der griechische Gott des Meeres?", "Poseidon", ["Zeus", "Hades", "Apollon"], "Bei den Römern hieß er Neptun."),
 ],
 [  # 26.10.
  ("Welches Tier kräht am Morgen?", "Hahn", ["Huhn", "Gans", "Ente"], "Der Hahn ist das männliche Huhn – er kräht."),
  ("Welcher Monat hat die wenigsten Tage?", "Februar", ["April", "November", "Juni"], "Der Februar hat 28 Tage, im Schaltjahr 29."),
  ("Welches Land ist für Tulpen und Windmühlen bekannt?", "Niederlande", ["Belgien", "Dänemark", "Schweiz"], "Die Niederlande sind einer der größten Blumenzüchter der Welt."),
  ("Wie heißt die Verwandlung einer Raupe in einen Schmetterling?", "Metamorphose", ["Mutation", "Fotosynthese", "Häutung"], "Aus der Raupe wird eine Puppe und daraus der Schmetterling."),
  ("Welcher Seefahrer erreichte 1492 Amerika?", "Christoph Kolumbus", ["Vasco da Gama", "Ferdinand Magellan", "Amerigo Vespucci"], "Kolumbus wollte eigentlich nach Indien – Amerika wurde später nach Amerigo Vespucci benannt."),
 ],
]
